### ISSUE TITLE
Window is not defined in node_modules

### ISSUE THREAD

**Issue by oyeanuj** [component/data-uri-to-blob#5]
Hi folks! It seems that `window` object is throwing the following error while starting webpack server. It seems similar to #3, but for the main `window` object. 

```
[piping] error given was: ReferenceError: window is not defined
[1]     at Object.<anonymous> (node_modules/data-uri-to-blob/index.js:6:12)
[1]     at Module._compile (module.js:571:32)
[1]     at Module._extensions..js (module.js:580:10)
[1]     at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:152:7)
```

I have this as a dependency via https://github.com/ianstormtaylor/slate-drop-or-paste-images/blob/4c1211616202ff680efe8c43566811a957a306e7/lib/load-image-file.js#L2

Thank you!

**Comment by oyeanuj** [comment]
@tj Can this be included inside the exported function?
https://github.com/component/data-uri-to-blob/blob/master/index.js#L2-L12

**Comment by joi762000** [comment]
I'm getting this error when starting webpack server, any solution?
